// child node traversal


//we get a list of eevry child node inside of the ul
//now here we see the distinction between nodes and elements
// addition to the five list items we got six text nodes
// this is because we wrote out our own html this wasn't generated by js
//te indentation between element nodes is counted in the dom tree as text nodes
let ul = document.querySelector("ul")

console.log(ul.childNodes)
console.log(ul.firstChild)
console.log(ul.lastChild)

// with this we get error because first is text and not list-items
// ul.firstChild.style.backgroundColor = "red" 

// with this we get error because last is text and not list-items
// ul.lastChild.style.backgroundColor = "brown" 

// this works
ul.childNodes[1].style.backgroundColor = "red" 

// this works
ul.childNodes[9].style.backgroundColor = "brown"

